### ISSUE TITLE
Sleep is a Windows function

### ISSUE THREAD

**Issue by adamsir** [DinoZ1729/Ray#12]
I was trying to compile this amazing work, but on Unix there is slight difference in sleep function.
`Sleep` is a Windows function
For Unix, `nanosleep` or `usleep`
https://stackoverflow.com/questions/10976176/c-error-sleep-was-not-declared-in-this-scope

This is the line, where I ran into problem with compiling on Mint and g++ 9.3.0.
https://github.com/DinoZ1729/Ray/blob/b6a9dbd6c74162ca9fea685ec0e7e7fcb5a7cf3c/main.cpp#L207

So, I replaced Sleep with usleep and uncomment `#include <unistd.h>` line and it solved my problem.

I'm not a cpp guy, but I think this issue is on point. What do you think?

**Comment by hlouzada** [comment]
The issue is indeed on point. @DinoZ1729 and @adamsir can u please check the merge #13.

**Comment by Seljumnik** [comment]
It's a very easy fix to make it compile on Linux:

Line 1
`#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif`

Line 203 (205 after edit)
`
    // sleeping to reduce frames count
    // maybe there is a better way than sleeping to sync
    #ifdef _WIN32
    Sleep(5);
    #else
    usleep(1/1000);
    #endif
`

This is my first time using GitHub. No idea how anything works. I fixed this myself, I tried to commit but it didn't go through I guess? Didn't say anything. Anyways, hope this helps :)

**Comment by Shroomerian** [comment]
I compiled the project in Linux with this issue in mind. The pull is #16 and it fixes #9 as well.

**Comment by Seljumnik** [comment]
Oh, you're fast... :D
For some reason when I pulled this of git hub yesterday it wouldn't work so I did the changes I described above.

**Comment by hlouzada** [comment]
@Seljumnik and @Shroomerian did u guys see my pr #13 ? I fixed this issue with a approach I had in mind when I added the sleep funtion... It was a temporary thing. And pr #15 also fixes this issue.

> Btw by using usleep(0.0001) I got beautiful fluent display. I had to resize the Terminal quite a bit and put it fullscreen, but it's wonderful. I am beyond amazed at what you've acomplished.

The best solution isn't using a fixed sleep or time because the thread takes different time for each loop and each cpu has also a different execution time.

> This is my first time using GitHub. No idea how anything works. I fixed this myself, I tried to commit but it didn't go through I guess? Didn't say anything. Anyways, hope this helps :)

Welcome to the world of open source and the github community 😁
