### ISSUE TITLE
how do I excute the file?

### ISSUE THREAD

**Issue by eitan07** [DinoZ1729/Ray#18]

**Comment by Shroomerian** [comment]
If you're interested in running the program you can check out my readme file at pull request #16. It's **Windows compile** method works on the current master branch.

**Comment by laambda** [comment]
I found in the commits that standard 17 was needed and solved the error "std :: clamp", ok, but when executing it the render does not adapt to the resolution of the terminal
"""
g++ -std=c++17 ball.h camera.cpp camera.h main.cpp matrix_operations.cpp matrix_operations.h vector.cpp vector.h -o ray

**Comment by laambda** [comment]
I found in commits (694813a) that standard 17 was needed and resolved the "std :: clamp" error, I used:
`g++ -std=c++17 ball.h camera.cpp camera.h main.cpp matrix_operations.cpp matrix_operations.h vector.cpp vector.h -o ray`
Ok. But when executing it the render **does not adapt to the resolution of the terminal**, that's the issue.
###
<img src="https://imgur.com/TOyNqIul.png" />

**Comment by skroll182** [comment]
Following steps worked for me in Ubuntu 20.04:
``` bash
git clone https://github.com/DinoZ1729/Ray
cd Ray
mkdir build && cd $_
cmake ..
make
./raytracer # Launch program
```

**Comment by hlouzada** [comment]
@laambda 
> But when executing it the render does not adapt to the resolution of the terminal, that's the issue.

Set text size to 8.

Also, ``cmake`` isn't required but recommended. As you did, using ``std=c++17`` and loading all external includes will do.

**Comment by eitan07** [comment]
Sorry for the typos, my English was so bad at the time, and I didn't knew how to use CMake or any C/C++ build system
BTW very cool project!
